#!/usr/bin/env bash

chosen_router=""

while getopts "r:" opt; do
    case "$opt" in
        r)
            chosen_router=$OPTARG

            if [ $chosen_router != "wrt1900acv2" ] && [ $chosen_router != "wrt610n" ]; then
                echo "-r must be either wrt1900acv2 or wrt610n"
                exit 1
            fi
            ;;
    esac
done

echo $chosen_router


if [ -z "$CLEARTEXT_FTI" ]; then
    echo "\$CLEARTEXT_FTI is empty. Please set it with: \`export CLEARTEXT_FTI=fti/xxxxxxx\`"
    exit 2
fi

ENCODED_FTI=$(echo -n $CLEARTEXT_FTI | xxd  -p)

gpg --batch --yes --decrypt-files *.secret.config.asc

scp *.config root@192.168.1.1:/tmp/
ssh root@192.168.1.1 "cat /tmp/$chosen_router.network.config | uci -m import network && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.network.config | uci -m import network && uci commit"
ssh root@192.168.1.1 "uci set network.wan.sendopts='0x4D:2b46535644534c5f6c697665626f782e496e7465726e65742e736f66746174686f6d652e4c697665626f7833 0x5a:00000000000000000000001a0900000558010341010d$ENCODED_FTI' && uci commit"
ssh root@192.168.1.1 "uci set network.wan6.sendopts='11:00000000000000000000001a0900000558010341010d$ENCODED_FTI  15:FSVDSL_livebox.Internet.softathome.livebox3 16:0000040e0005736167656d' && uci commit"
echo "Waiting for router to reboot..."&& ssh root@192.168.1.1 "reboot" && sleep 45

scp *.config root@192.168.1.1:/tmp/
ssh root@192.168.1.1 "opkg update && opkg install block-mount ca-certificates ddns-scripts_no-ip_com kmod-fs-ntfs kmod-fs-vfat luci-app-ddns luci-app-samba luci-app-simple-adblock luci-app-uhttpd luci-app-upnp luci-app-wol luci-ssl sslh wget"
ssh root@192.168.1.1 "cat /tmp/common.dhcp.config | uci -m import dhcp && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.dhcp.secret.config | uci -m import dhcp && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.ddns.secret.config | uci -m import ddns && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.firewall.config | uci -m import firewall && uci commit"
# no merging for simple-adblock
ssh root@192.168.1.1 "cat /tmp/common.simple-adblock.config | uci import simple-adblock && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.sslh.config | uci -m import sslh && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.system.config | uci -m import system && uci commit"
ssh root@192.168.1.1 "uci del uhttpd.main.listen_https && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.uhttpd.config | uci -m import uhttpd && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.uhttpd.secret.config | uci -m import uhttpd && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.upnpd.config | uci -m import upnpd && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.wireless.config | uci -m import wireless && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.wireless.secret.config | uci -m import wireless && uci commit"
ssh root@192.168.1.1 "wget --output-document=/etc/dropbear/authorized_keys https://raw.githubusercontent.com/nagromc/dotfiles/master/ssh/authorized_keys"
scp common.dropbear.config root@192.168.1.1:/tmp/
ssh root@192.168.1.1 "cat /tmp/common.dropbear.config | uci -m import dropbear && uci commit && /etc/init.d/dropbear restart"
scp rc.local root@192.168.1.1:/etc/
ssh root@192.168.1.1 "echo 'morgan:*:1000:65534:morgan:/var:/bin/false' >> /etc/passwd"
scp samba-passwd root@192.168.1.1:/tmp/samba-passwd
ssh root@192.168.1.1 "smbpasswd -s -a morgan < /tmp/samba-passwd"
