#!/usr/bin/env bash

chosen_router=""

while getopts "r:" opt; do
    case "$opt" in
        r)
            chosen_router=$OPTARG

            if [ $chosen_router != "wrt1900acv2" ] && [ $chosen_router != "wrt610n" ]; then
                echo "-r must be either wrt1900acv2 or wrt610n"
                exit 1
            fi
            ;;
    esac
done

echo $chosen_router


ENCODED_FTI=$(echo -n $CLEARTEXT_FTI | xxd  -p)

gpg --batch --yes --output common.dhcp.secret.config --decrypt common.dhcp.secret.config.asc
gpg --batch --yes --output common.ddns.secret.config --decrypt common.ddns.secret.config.asc
gpg --batch --yes --output common.wireless.secret.config --decrypt common.wireless.secret.config.asc
scp *.config root@192.168.1.1:/tmp/
ssh root@192.168.1.1 "cat /tmp/$chosen_router.network.config | uci -m import network && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.dhcp.config | uci -m import dhcp && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.dhcp.secret.config | uci -m import dhcp && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.ddns.secret.config | uci -m import ddns && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.network.config | uci -m import network && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.sslh.config | uci -m import sslh && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.system.config | uci -m import system && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.wireless.config | uci -m import wireless && uci commit"
ssh root@192.168.1.1 "cat /tmp/common.wireless.secret.config | uci -m import wireless && uci commit"
ssh root@192.168.1.1 "uci set network.wan.sendopts='0x4D:2b46535644534c5f6c697665626f782e496e7465726e65742e736f66746174686f6d652e4c697665626f7833 0x5a:0000000000000000000000$ENCODED_FTI' && uci commit"
ssh root@192.168.1.1 "uci set network.wan6.sendopts='11:0000000000000000000000$ENCODED_FTI  15:FSVDSL_livebox.Internet.softathome.livebox3 16:0000040e0005736167656d' && uci commit"
echo "Waiting for router to reboot..."&& ssh root@192.168.1.1 "reboot" && sleep 45
ssh root@192.168.1.1 "opkg update && opkg install ca-certificates ddns-scripts_no-ip_com luci-app-ddns luci-app-wol sslh wget"
ssh root@192.168.1.1 "wget --output-document=/etc/dropbear/authorized_keys https://raw.githubusercontent.com/nagromc/dotfiles/master/ssh/authorized_keys"
scp common.dropbear.config root@192.168.1.1:/tmp/
ssh root@192.168.1.1 "cat /tmp/common.dropbear.config | uci -m import dropbear && uci commit && /etc/init.d/dropbear restart"
